[package]
name = "tensor"
version = "0.1.0"
edition = "2021"
build = "src/build.rs"
repository = "https://github.com/TrainPioneers/fast_tensor"
authors = ["Artur arturmisiurev@gmail.com"]
include = ["/instructions/wgpu/"]

[features]
default = ["cpu"]
cuda = ["cust"]
wgpu = ["dep:wgpu"]
cpu = []


[dependencies]
wgpu = { version = "23.0.0", optional = true }
cust = { version = "0.3.2", optional = true }

bytemuck = "1.19.0"
futures = "0.3.31"
futures-intrusive = "0.5.0"
once_cell = "1.20.2"

