[package]
name = "fast_tensor"
version = "0.1.0"
edition = "2021"
build = "src/build.rs"
repository = "https://github.com/TrainPioneers/fast_tensor"
authors = ["Artur arturmisiurev@gmail.com"]
include = ["/instructions/wgpu/"]

[dependencies]
core = { path = "crates/core" }
tensor = { path = "crates/tensor" }

[features]
default = ["core/cpu"]
cuda = ["core/cuda"]
wgpu = ["core/wgpu"]
cpu = ["core/cpu"]

[workspace]
members = [
    "crates/cuda_vm",
    "crates/wgpu_vm",
    "crates/tensor",
    "crates/core",
    "crates/cpu_vm"
    , "crates/util"]
