[package]
name = "tensor"
version = "0.1.0"
edition = "2021"
build = "src/build.rs"
repository = "https://github.com/TrainPioneers/fast_tensor"
authors = ["Artur arturmisiurev@gmail.com"]
include = ["/instructions/wgpu/"]

[features]
default = ["cpu_vm"]
cuda = ["cuda_vm"]
wgpu = ["wgpu_vm"]
cpu = ["cpu_vm"]


[dependencies]
core = { path = "crates/core" }
cpu_vm = { path = "crates/cpu_vm" }
cuda_vm = { path = "crates/cuda_vm" }
tensor = { path = "crates/tensor" }
wgpu_vm = { path = "crates/wgpu_vm" }

[workspace]
members = [
    "crates/cuda_vm",
    "crates/wgpu_vm",
    "crates/tensor",
    "crates/core",
    "crates/cpu_vm"
]
