[package]
name = "tensor"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "23.0.0"
bytemuck = "1.19.0"
futures = "0.3.31"
futures-intrusive = "0.5.0"
once_cell = "1.20.2"
cust = { version = "0.3.2", optional = true }
