[package]
name = "wgpu_vm"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
wgpu = "23.0.0"
bytemuck = "1.19.0"
futures = "0.3.31"
futures-intrusive = "0.5.0"
util = {path = "../util"}